version: '3'
services:
  app:
    restart: unless-stopped
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    container_name: singalweb_app
#    volumes:
#      - ./app:/app
    ports:
      - "5000:5000"

  mysql:
    restart: unless-stopped
    image: mysql/mysql-server:5.6
    container_name: singalweb_mysql

    volumes:
      - ./db:/docker-entrypoint-initdb.d/

#    ports:
#      - "3308:3306"

    environment:
      - "MYSQL_ROOT_PASSWORD=12019054Aroot"
      - "MYSQL_DATABASE=SingalPageWebSql"
      - "TZ=Asia/Shanghai"
